Release workflow
bitwarden/dotnet-extensions pull request #50
Opened 2024-12-03 20:02 UTC by justindbaur

## 🎟️ Tracking

## 📔 Objective

My try at a release workflow where you can release a single package and have it create a PR auto bumping to the next version based on the type of release.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

2024-12-03 20:49 UTC, withinfocus requested changes
This is hot! I like the update script making this a bit more straightforward and using the capabilities of .NET. Few things to approve, then BRE may also want to take a look.

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +env:
🎨 Would be good to define permissions this workflow needs above, to scope the token.

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +    name: Build Artifact
```suggestion
    name: Build artifacts
```

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +      - name: Get Current Version
```suggestion
      - name: Get current version
```

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +      # Creating this github release is what should trigger the actual releasing of the nuget package
⛏️ I'd make this a statement such as `# Creating a GitHub Release triggers package publishing`.

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +            // configure git
```suggestion
            // Configure Git
```

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +              body: "WIP",
❓ Does `generate_release_notes` handle this?

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +
⛏️ Clean up extra newlines. I thought the workflow linter would catch this but I guess not.

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +      - name: Run Version Bumper
```suggestion
      - name: Bump version
```

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +          echo "NEW_VERSION=$(./scrips/UpdatePackageVersion.ps1 -PackageName $env:PACKAGE_NAME -BumpType $env:BUMP_TYPE)" >> $env:GITHUB_OUTPUT
```suggestion
          echo "NEW_VERSION=$(./scripts/UpdatePackageVersion.ps1 -PackageName $env:PACKAGE_NAME -BumpType $env:BUMP_TYPE)" >> $env:GITHUB_OUTPUT
```

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +            // configure git
```suggestion
            // Configure Git
```

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +      - name: Create PR
💭 Should the PR be made before the Release?

2024-12-03 20:49 UTC, withinfocus commented on .github/workflows/release.yml
> +            // add and commit changes
```suggestion
            // Add and commit changes
```

2024-12-04 16:26 UTC, justindbaur commented on .github/workflows/release.yml
> +              body: "WIP",
I don't think so, I think what this is going to add is add `[the release tag]..[tag for this release]` so you can view all commits between. But since we are going to release different packages from this that won't work so great. I think what I want to have happen is that the version bumper below is going to append a header to a `CHANGELOG.md` file. Then you are expected to write in details for your PR into the changelog. Then the release body can be a link to `https://github.com/bitwarden/dotnet-extensions/blob/[PackageName]_v[Version]/extensions/[PackageName]/CHANGELOG.md#[Version]`. This is sort of how https://github.com/Azure/azure-sdk/blob/main/docs/policies/releases.md#change-logs does it. Since I don't expect a barage of commits to any one package from people once release I'm not worried about merge conflicts to any particular `CHANGELOG.md` file.

2024-12-04 16:41 UTC, justindbaur commented on .github/workflows/release.yml
> +      - name: Create PR
No, this is creating a PR for bumping the version for the _next_ release. I wouldn't want the commit for doing so on the released tag. See: https://github.com/Azure/azure-sdk/blob/main/docs/policies/releases.md#incrementing-after-release as my inspiration.

2024-12-04 16:46 UTC, justindbaur commented on .github/workflows/release.yml
> +env:
Gave it a shot in 3ed02b66ff9dff608cbc5d54e9803fd36360edd5 I'm not sure if I also need `packaging: write` since I create a release that will hopefully do packaging but it's not actually done here so I would imagine only the other workflow needs that permission.

2024-12-04 19:32 UTC, withinfocus approved these changes
Makes sense to me at this point. Not sure if we want to try it before BRE reviews or not.

2024-12-04 19:43 UTC, justindbaur commented
> Not sure if we want to try it before BRE reviews or not.

@withinfocus I'd really like to just merge it to `main` because I kinda highly doubt it will work in the first go and once it's on `main` I should be able to run the workflow on a feature branch to debug it more. I also think the amount of things I could break with this are pretty low, (just spamming a couple package update to nuget), but if you think we should then I am happy to add their review.

2024-12-04 19:44 UTC, withinfocus commented
Let's do it -- team autonomy and the CI / CD partnership model!

2024-12-04 19:46 UTC, merged